name: IzmYuta
permalink: :year/:month/:day/:title
baseurl: /TIL_pages

# Your blog's start year and this year, showed in the footer left
# start is optional
# start: 2022
now: 2023
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : y.izumi@4nonome.com
  github : IzmYuta
  twitter : IzmYuta

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
   Posts: "/posts"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

