on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/"
      - "README.md"
jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: bundle install
      run: |
        bundle config set path 'vendor/bundle'
        bundle install
    - name: Jekyll Build
      run: bundle exec jekyll build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.TIL_GITHUB_ACCESS_TOKEN }}
        publish_dir: .
