name: copy *.md from TIL
on:
  repository_dispatch:
    types: [target-updated]
jobs:
  copy-target:
    name: copy *.md
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone TIL
        uses: actions/checkout@v2
        with:
          repository: IzmYuta/TIL
          path: TIL
          token: ${{ secrets.TIL_GITHUB_ACCESS_TOKEN }}
      - name: copy *.md
        run: cp -r TIL/TILs/*/. _posts/
      - name: add fileinfo
        run: find /_posts/ -type f -name "*.md" | xargs sed '1i ---짜nlayout: post짜ntitle: "python"짜ndate: 2023-08-01짜n---'
      - name: clean TIL
        run: rm -rf TIL
      - name: create PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TIL_GITHUB_ACCESS_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: 'copy *.md'
          branch: copy_target
          branch-suffix: timestamp
          delete-branch: true
          title: 'updated *.md'
      # - name: Enable auto-merge for Steward PRs
      #   env:
      #     GH_TOKEN: ${{ secrets.TIL_GITHUB_ACCESS_TOKEN }}
      #   run: gh pr merge --merge --auto ${{ steps.cpr.outputs.pull-request-url }}
