name: copy *.md from TIL
on:
  repository_dispatch:
    types: [target-updated]
jobs:
  copy-target:
    name: copy *.md
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: clone TIL
        uses: actions/checkout@v3
        with:
          repository: IzmYuta/TIL
          path: TIL
          token: ${{ secrets.TIL_GITHUB_ACCESS_TOKEN }}
      - name: add fileinfo
        run: |
          find TIL/TILs/*/. -type f -name "*.md" | while read -r md_file; do
            category=$(echo "$md_file" | awk -F'/TILs/' '{print $2}' | cut -d'/' -f1)
            filename=$(basename "$md_file")
            title=$(echo "$filename" | cut -d'-' -f4- | sed 's/\.md$//')
            date=$(echo "$filename" | cut -d'-' -f1-3)
            echo "---" > tmp_file
            echo "layout: post" >> tmp_file
            echo "title: \"$title\"" >> tmp_file
            echo "date: $date" >> tmp_file
            echo "category: $category" >> tmp_file
            echo "excerpt: \"\"" >> tmp_file
            echo "---" >> tmp_file
            cat "$md_file" >> tmp_file
            mv tmp_file "$md_file"
          done
      - name: copy *.md
        run: cp -r TIL/TILs/*/. _posts/
      - name: clean TIL
        run: rm -rf TIL
      - name: create PR
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TIL_GITHUB_ACCESS_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: 'copy markdown files'
          branch: copy_target
          branch-suffix: timestamp
          delete-branch: true
          title: 'updated markdown files'
      - name: Enable auto-merge for Steward PRs
        env:
          GH_TOKEN: ${{ secrets.TIL_GITHUB_ACCESS_TOKEN }}
        run: gh pr merge --merge --auto ${{ GITHUB_OUTPUT }}
